name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Hugo
        run: |
          HUGO_VERSION="0.121.0"
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          tar -xf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          mkdir -p $RUNNER_TOOL_CACHE/hugo/${HUGO_VERSION}-x64
          mv hugo $RUNNER_TOOL_CACHE/hugo/${HUGO_VERSION}-x64/hugo
          rm hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz

      - name: Load environment variables
        run: |
          source ${{ github.workspace }}/.env
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Build site
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HUGO_BOOK }}
          publish_dir: ./static
